import type { NextConfig } from "next";
import path from "node:path";

/** Deliberately minimal.
 *
 *  The portfolio ships its own responsive derivatives (AVIF + WebP at fixed
 *  widths, generated by `scripts/images.mjs` and served from `public/img` via
 *  plain <picture> elements), so next/image and its optimizer are not in play.
 *  Nothing here needs a custom loader, rewrite or runtime. */
const nextConfig: NextConfig = {
  reactStrictMode: true,
  /* Pin file tracing to this directory. Without it Next walks up and picks a
     lockfile outside the repo as the workspace root, which makes the traced
     output on Vercel wrong. */
  outputFileTracingRoot: path.join(import.meta.dirname, "./"),
};

export default nextConfig;
