// GENERATED by scripts/images.mjs — do not edit by hand.
export interface ImageMeta {
  widths: number[];
  width: number;
  height: number;
  aspect: number;
}

export const images = {
  "hero-cutout": {
    "widths": [
      560,
      860,
      1122
    ],
    "aspect": 0.8003,
    "width": 1122,
    "height": 1402
  },
  "about-bw": {
    "widths": [
      480,
      760,
      1122
    ],
    "aspect": 0.8003,
    "width": 1122,
    "height": 1402
  },
  "motion-portrait": {
    "widths": [
      480,
      760,
      1122
    ],
    "aspect": 0.8003,
    "width": 1122,
    "height": 1402
  },
  "atelier27-desktop": {
    "widths": [
      900,
      1500,
      2100
    ],
    "aspect": 1.6,
    "width": 2400,
    "height": 1500
  },
  "atelier27-phone": {
    "widths": [
      420,
      700,
      860
    ],
    "aspect": 0.4614,
    "width": 860,
    "height": 1864
  },
  "matura-desktop": {
    "widths": [
      900,
      1500,
      2100
    ],
    "aspect": 1.6,
    "width": 2400,
    "height": 1500
  },
  "matura-phone": {
    "widths": [
      420,
      700,
      860
    ],
    "aspect": 0.4614,
    "width": 860,
    "height": 1864
  },
  "forge-desktop": {
    "widths": [
      900,
      1500,
      2100
    ],
    "aspect": 1.6,
    "width": 2400,
    "height": 1500
  },
  "forge-phone": {
    "widths": [
      420,
      700,
      860
    ],
    "aspect": 0.4614,
    "width": 860,
    "height": 1864
  },
  "saferoad-desktop": {
    "widths": [
      900,
      1500,
      2100
    ],
    "aspect": 1.6,
    "width": 2400,
    "height": 1500
  },
  "saferoad-phone": {
    "widths": [
      420,
      700,
      860
    ],
    "aspect": 0.4614,
    "width": 860,
    "height": 1864
  },
  "law-desktop": {
    "widths": [
      900,
      1500,
      2100
    ],
    "aspect": 1.6,
    "width": 2400,
    "height": 1500
  },
  "law-phone": {
    "widths": [
      420,
      700,
      860
    ],
    "aspect": 0.4614,
    "width": 860,
    "height": 1864
  },
  "english-desktop": {
    "widths": [
      900,
      1500,
      2100
    ],
    "aspect": 1.6,
    "width": 2400,
    "height": 1500
  },
  "english-phone": {
    "widths": [
      420,
      700,
      860
    ],
    "aspect": 0.4614,
    "width": 860,
    "height": 1864
  },
  "matura2027-desktop": {
    "widths": [
      900,
      1500,
      2100
    ],
    "aspect": 1.6,
    "width": 2400,
    "height": 1500
  },
  "matura2027-phone": {
    "widths": [
      420,
      700,
      860
    ],
    "aspect": 0.4614,
    "width": 860,
    "height": 1864
  },
  "case-before": {
    "widths": [
      700,
      1320
    ],
    "aspect": 1.2754,
    "width": 1320,
    "height": 1035
  },
  "case-after": {
    "widths": [
      700,
      1426
    ],
    "aspect": 1.2928,
    "width": 1426,
    "height": 1103
  },
  "ig-before": {
    "widths": [
      600
    ],
    "aspect": 1.1654,
    "width": 592,
    "height": 508
  },
  "ig-after": {
    "widths": [
      600,
      1000
    ],
    "aspect": 1.0662,
    "width": 1320,
    "height": 1238
  }
} as const satisfies Record<string, ImageMeta>;

export type ImageName = keyof typeof images;
