// Generates responsive AVIF + WebP derivatives from the approved source PNGs.
// Sources live one level up, outside the app; output is committed to public/img.
import sharp from "sharp";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const SRC = path.resolve(import.meta.dirname, "../");
const OUT = path.resolve(import.meta.dirname, "../public/img");

/** width ladders tuned to how large each image ever renders */
const JOBS = [
  // Matted cutout: keeps its alpha so the figure sits on the page with no
  // rectangle. AVIF/WebP both carry the alpha channel through.
  { src: "hero-cutout.png", name: "hero-cutout", widths: [560, 860, 1122], alpha: true },
  { src: "about-bw.png", name: "about-bw", widths: [480, 760, 1122] },
  { src: "motion-portrait.png", name: "motion-portrait", widths: [480, 760, 1122] },

  // Selected work — screenshots captured from the five live sites.
  { src: "captures/atelier27-desktop.png", name: "atelier27-desktop", widths: [900, 1500, 2100] },
  { src: "captures/atelier27-phone.png", name: "atelier27-phone", widths: [420, 700, 860] },
  { src: "captures/matura-desktop.png", name: "matura-desktop", widths: [900, 1500, 2100] },
  { src: "captures/matura-phone.png", name: "matura-phone", widths: [420, 700, 860] },
  { src: "captures/forge-desktop.png", name: "forge-desktop", widths: [900, 1500, 2100] },
  { src: "captures/forge-phone.png", name: "forge-phone", widths: [420, 700, 860] },
  { src: "captures/saferoad-desktop.png", name: "saferoad-desktop", widths: [900, 1500, 2100] },
  { src: "captures/saferoad-phone.png", name: "saferoad-phone", widths: [420, 700, 860] },
  { src: "captures/law-desktop.png", name: "law-desktop", widths: [900, 1500, 2100] },
  { src: "captures/law-phone.png", name: "law-phone", widths: [420, 700, 860] },
  { src: "captures/english-desktop.png", name: "english-desktop", widths: [900, 1500, 2100] },
  { src: "captures/english-phone.png", name: "english-phone", widths: [420, 700, 860] },
];

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

const manifest = {};
for (const job of JOBS) {
  const input = path.join(SRC, job.src);
  const meta = await sharp(input).metadata();
  const widths = job.widths.filter((w) => w <= meta.width);
  if (!widths.includes(Math.min(...job.widths))) widths.unshift(Math.min(...job.widths));

  for (const w of widths) {
    const pipe = sharp(input).resize({ width: w, withoutEnlargement: true });
    // screenshots carry fine UI text, so they get a higher quality floor than
    // the photography does
    const q = job.alpha ? { avif: 60, webp: 82 } : { avif: 64, webp: 86 };
    await pipe.clone().avif({ quality: q.avif, effort: 6 }).toFile(path.join(OUT, `${job.name}-${w}.avif`));
    await pipe.clone().webp({ quality: q.webp, effort: 5 }).toFile(path.join(OUT, `${job.name}-${w}.webp`));
  }
  manifest[job.name] = {
    widths,
    aspect: +(meta.width / meta.height).toFixed(4),
    width: meta.width,
    height: meta.height,
  };
  console.log(`${job.name.padEnd(18)} ${meta.width}x${meta.height} -> ${widths.join(", ")}`);
}

const files = await readdir(OUT);

// keep the typed manifest in lockstep with what actually landed on disk
const ts =
  `// GENERATED by scripts/images.mjs — do not edit by hand.\n` +
  `export interface ImageMeta {\n  widths: number[];\n  width: number;\n  height: number;\n  aspect: number;\n}\n\n` +
  `export const images = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, ImageMeta>;\n\n` +
  `export type ImageName = keyof typeof images;\n`;
await writeFile(new URL("../data/images.ts", import.meta.url), ts);

console.log(`\n${files.length} files, data/images.ts written`);
